/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedLivroRouteImport } from './routes/_authenticated/livro'
import { Route as AuthenticatedLinhaDoTempoRouteImport } from './routes/_authenticated/linha-do-tempo'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedCriancaRouteImport } from './routes/_authenticated/crianca'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLivroRoute = AuthenticatedLivroRouteImport.update({
  id: '/livro',
  path: '/livro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLinhaDoTempoRoute =
  AuthenticatedLinhaDoTempoRouteImport.update({
    id: '/linha-do-tempo',
    path: '/linha-do-tempo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCriancaRoute = AuthenticatedCriancaRouteImport.update({
  id: '/crianca',
  path: '/crianca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crianca': typeof AuthenticatedCriancaRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/linha-do-tempo': typeof AuthenticatedLinhaDoTempoRoute
  '/livro': typeof AuthenticatedLivroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crianca': typeof AuthenticatedCriancaRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/linha-do-tempo': typeof AuthenticatedLinhaDoTempoRoute
  '/livro': typeof AuthenticatedLivroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/crianca': typeof AuthenticatedCriancaRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/linha-do-tempo': typeof AuthenticatedLinhaDoTempoRoute
  '/_authenticated/livro': typeof AuthenticatedLivroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/crianca' | '/inicio' | '/linha-do-tempo' | '/livro'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/crianca' | '/inicio' | '/linha-do-tempo' | '/livro'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/crianca'
    | '/_authenticated/inicio'
    | '/_authenticated/linha-do-tempo'
    | '/_authenticated/livro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/livro': {
      id: '/_authenticated/livro'
      path: '/livro'
      fullPath: '/livro'
      preLoaderRoute: typeof AuthenticatedLivroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/linha-do-tempo': {
      id: '/_authenticated/linha-do-tempo'
      path: '/linha-do-tempo'
      fullPath: '/linha-do-tempo'
      preLoaderRoute: typeof AuthenticatedLinhaDoTempoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crianca': {
      id: '/_authenticated/crianca'
      path: '/crianca'
      fullPath: '/crianca'
      preLoaderRoute: typeof AuthenticatedCriancaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCriancaRoute: typeof AuthenticatedCriancaRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedLinhaDoTempoRoute: typeof AuthenticatedLinhaDoTempoRoute
  AuthenticatedLivroRoute: typeof AuthenticatedLivroRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCriancaRoute: AuthenticatedCriancaRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedLinhaDoTempoRoute: AuthenticatedLinhaDoTempoRoute,
  AuthenticatedLivroRoute: AuthenticatedLivroRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
